import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Julius Answer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <container className={styles.container}>
           <div className={styles.titulo}>
             <h1>Julius Answer</h1>
           </div>
           <div className={styles.mensagem}>
            <input id="" name="mensagem" placeholder="Insira sua mensagem" />
           </div>
           <button onclick="" className={styles.button}>Traduzir mensagem</button>
              <div onload="">
              <ul id="" className={styles.lista}>

               </ul>
              </div>
        </container>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
