import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Lista from '../components/lista'
import Title from "../components/title";

export default function Home() {
  const [mensagem, setMensagem] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Julius Answer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
            <Title texto="Julius Answer"/>
          <div className={styles.mensagem}>
            <input
              id=""
              name="mensagem"
              placeholder="Insira sua mensagem"
              onChange={(ev) => setMensagem(ev.target.value)}
            />
          </div>
    
           <Lista mensagem={mensagem} />
  
  
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
